version: '3'

services:

  frontend-full:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "5000:5000"
    volumes:
      - "../config/nginx/conf.d:/etc/nginx/conf.d"
      - "../config/nginx/errors:/var/www/html/errors"
      - "../../frontend/build:/var/www/html/front"
      - "../../admin/build:/var/www/html/admin"

  backend-full:
    build: "../../backend"
    restart: always
    volumes:
      - "../../backend:/app"